//> using publish.organization "io.github.alexarchambault.tmp"
//> using publish.name "visual-cpp-helper"
//> using publish.license "Apache-2.0"
//> using publish.url "https://github.com/scala-cli/visual-cpp-helper"
//> using publish.versionControl "github:scala-cli/visual-cpp-helper"
//> using publish.developer "Alex Archambault|alexandre.archambault@gmail.com|https://github.com/alexarchambault"

// FIXME Actually ci only (needs VirtusLab/scala-cli#926)
//> using publish.computeVersion "git:tag"
//> using publish.repository "central-s01"
//> using publish.user "env:PUBLISH_USER"
//> using publish.password "env:PUBLISH_PASSWORD"
//> using publish.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
//> using publish.ci.computeVersion "git:tag"
//> using publish.ci.repository "central-s01"
//> using publish.ci.user "env:PUBLISH_USER"
//> using publish.ci.password "env:PUBLISH_PASSWORD"
//> using publish.ci.secretKey "env:PUBLISH_SECRET_KEY"
//> using publish.ci.secretKeyPassword "env:PUBLISH_SECRET_KEY_PASSWORD"
